version: "2.3"

services:
  client:
    build: ./web
    container_name: client
    volumes:
      - ./web:/app
    ports:
      - 4200:4200
    working_dir: "/app"
    command: "yarn start --host 0.0.0.0"
    restart: unless-stopped

  server:
    build: ./serverless/python
    container_name: server
    volumes:
      - ./serverless/python:/app
    ports:
      - 5000:5000
    environment:
      - BUCKET_NAME=tcg-bucket
      - FOLDER_UPLOAD=upload_part
      - ENDPOINT_URL=http://10.1.38.246:9000
      - AWS_ACCESS_ID=tcg
      - AWS_SECRET_KEY=3e6eMbz7NRBPfjYf
    restart: unless-stopped
