version: "2.3"

services:
  client:
    build: ./web
    container_name: client
    volumes:
      - ./web:/app
    ports:
      - 4200:4200
    working_dir: "/app"
    command: "yarn start --host 0.0.0.0"
    restart: unless-stopped

  server:
    build: ./serverless/python
    container_name: server
    volumes:
      - ./serverless/python:/app
    ports:
      - 5000:5000
    environment:
      - BUCKET_NAME=
      - FOLDER_UPLOAD=
      - ENDPOINT_URL=
      - AWS_ACCESS_ID=
      - AWS_SECRET_KEY=
    restart: unless-stopped
